import google.generativeai as genai
import os

from dotenv import load_dotenv

load_dotenv()

# Configure Gemini API
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

# Generate a story using Gemini API based on an image description.
def get_gemini_response(image_description):
    try:
        model = genai.GenerativeModel('gemini-1.5-flash')
        prompt = (
            f"Describe the cultural or heritage significance of the following place: {image_description}. "
            "Provide a brief introduction about the place, followed by an interesting and unique story or fact about it."
        )
        response = model.generate_content([prompt])
        print(response)
        if response and response.candidates:
            return response.candidates[0].content.parts[0].text
        return "No response generated by the model."
    except Exception as e:
        return f"Error during Gemini API call: {e}"
